### ISSUE TITLE
Could you reorganize the paper list 

### ISSUE THREAD

**Issue by Doragd** [txsun1997/nlp-paradigm-shift#1]
hi, sun.
Thanks for your insightful survey work for the paradigm shift in NLP.
The papers in this repo only have the published year and authors' names.
Could you reorganize the paper list to offer more details, e.g. the titles?

**Comment by SinclairCoder** [comment]
> hi, sun. Thanks for your insightful survey work for the paradigm shift in NLP. The papers in this repo only have the published year and authors' names. Could you reorganize the paper list to offer more details, e.g. the titles?

Hi, I had summarized the NLP-paradigm-shifting-related reading list two months ago which may be imperfect comparing with this nice repo but with a better way to present paper info. For more info please visit [NLP-ParadigmShiftingPapers](https://github.com/SinclairCoder/NLP-ParadigmShiftingPapers)

**Comment by txsun1997** [comment]
Thanks for your comments. The published year and the authors in the table are hyperlinked, so you can access the exact paper for more details. Besides, we are considering maintaining a more detailed paper list like [NLP-ParadigmShiftingPapers](https://github.com/SinclairCoder/NLP-ParadigmShiftingPapers).
