### ISSUE TITLE
contribute to this repo

### ISSUE THREAD

**Issue by SinclairCoder** [txsun1997/nlp-paradigm-shift#2]
Hi, thanks for your greatly insightful survey. I had summarized related papers two months ago which may not be as comprehensive as yours. Sincerely hope it will contribute to this nice repo.  For more info please visit [NLP-ParadigmShiftingPapers](https://github.com/SinclairCoder/NLP-ParadigmShiftingPapers).

**Comment by txsun1997** [comment]
Thanks for the valuable contribution! I've read your nice repo and found many papers that we missed in our paper. The papers that we missed will be included in the website and the next version of our paper, and of course, we will acknowledge your helpful contribution.

**Comment by SinclairCoder** [comment]
> Thanks for the valuable contribution! I've read your nice repo and found many papers that we missed in our paper. The papers that we missed will be included in the website and the next version of our paper, and of course, we will acknowledge your helpful contribution.

it's my great honor to be able to contribute to this work.  I like this work very much.  If possible, I will continue to contribute to this work to make it more perfect.
